# Generated by Django 4.2.7 on 2024-09-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsectors', to='fsw_api.sector')),
            ],
            options={
                'unique_together': {('sector', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TopCompanyMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=10)),
                ('price_change', models.FloatField()),
                ('last_close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('latest_close_date', models.DateField()),
            ],
            options={
                'unique_together': {('symbol', 'classification', 'period', 'latest_close_date')},
            },
        ),
        migrations.CreateModel(
            name='SubsectorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('market_cap', models.JSONField(blank=True, null=True)),
                ('stability', models.JSONField(blank=True, null=True)),
                ('valuation', models.JSONField(blank=True, null=True)),
                ('growth', models.JSONField(blank=True, null=True)),
                ('companies', models.JSONField(blank=True, null=True)),
                ('subsector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='fsw_api.subsector')),
            ],
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.ManyToManyField(related_name='subindustries', to='fsw_api.industry')),
            ],
        ),
        migrations.CreateModel(
            name='MostTradedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('volume', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('adjusted', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='fsw_api.subsector'),
        ),
        migrations.CreateModel(
            name='IDXMarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idx_total_market_cap', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.JSONField(blank=True, null=True)),
                ('valuation', models.JSONField(blank=True, null=True)),
                ('future', models.JSONField(blank=True, null=True)),
                ('financials', models.JSONField(blank=True, null=True)),
                ('dividend', models.JSONField(blank=True, null=True)),
                ('management', models.JSONField(blank=True, null=True)),
                ('ownership', models.JSONField(blank=True, null=True)),
                ('peers', models.JSONField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='fsw_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chg_7d', models.FloatField(blank=True, null=True)),
                ('chg_30d', models.FloatField(blank=True, null=True)),
                ('chg_90d', models.FloatField(blank=True, null=True)),
                ('chg_365d', models.FloatField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='fsw_api.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='index',
            field=models.ManyToManyField(to='fsw_api.index'),
        ),
        migrations.AddField(
            model_name='company',
            name='subindustry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='fsw_api.subindustry'),
        ),
        migrations.AddField(
            model_name='company',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='fsw_api.subsector'),
        ),
        migrations.CreateModel(
            name='TopRankedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
                ('subsector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranked_companies', to='fsw_api.subsector')),
            ],
            options={
                'unique_together': {('symbol', 'classification', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TopCompanyGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=50)),
                ('yoy_growth', models.FloatField()),
                ('subsector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_companies', to='fsw_api.subsector')),
            ],
            options={
                'unique_together': {('symbol', 'classification')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('subsector', 'name')},
        ),
        migrations.CreateModel(
            name='IndexDailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_transactions', to='fsw_api.index')),
            ],
            options={
                'unique_together': {('index', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('market_cap', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_transactions', to='fsw_api.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('symbol', 'subsector', 'subindustry')},
        ),
    ]
